### ISSUE TITLE
SPDX License headers

### ISSUE THREAD

**Issue by redfast00** [charlesnicholson/nanocobs#53]
Thank you for the extremely free license for this, this definitely makes my life easier. For me, it would be useful if the license information is tracked per-file with standard SPDX headers. https://spdx.dev/learn/handling-license-info/#why. Is this something you would be willing to implement? I can also make a PR if that's easier for you.

`// SPDX-License-Identifier: Unlicense OR 0BSD`

**Comment by charlesnicholson** [comment]
Oh, cool, I hadn't seen SPDX before. Sure, I'd happily take a PR for that if you're interesting in opening one!
