### ISSUE TITLE
Confusing `// Now, fill buf[1 .. 63] with whatever data you want.` in documentation

### ISSUE THREAD

**Issue by redfast00** [charlesnicholson/nanocobs#63]
In the README, under [encoding tiny frames](https://github.com/charlesnicholson/nanocobs?tab=readme-ov-file#encoding-tiny-frames) there is a comment `// Now, fill buf[1 .. 63] with whatever data you want.`

When I first read this, it wasn't entirely clear what was meant by this; by reading the code, I understand that this `1 .. 63` is inclusive of the beginning, but not of the end (so you can't fill in `buf[63]`). Maybe this could be made clearer:

`// Now, fill in buf[1] up to and including buf[62] (so 64 - 2 = 62 bytes of payload data)`

**Comment by charlesnicholson** [comment]
Ah, great catch, thanks! Your assessment is correct; it's an off-by-one bug in the docs and not anything deeper in the library :). Sorry about the confusion! I'll fix it asap, or if you want to open a PR against it I'll happily take it. (I think you can do that entirely from the UI for readme changes)

**Comment by charlesnicholson** [comment]
Add your (user)name to the contributors list too if you like!
